#This is a new template that will automatically create a private EC2 Instance 
AWSTemplateFormatVersion: '2010-09-09'
Description: Example CloudFormation Template with EC2, IAM, and RDS

Resources:

  MyPrivateVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Sub '10.255.0.0/16'
      EnableDnsHostnames: true
      EnableDnsSupport: true

  VpcCidrBlockIpv6:
    Type: 'AWS::EC2::VPCCidrBlock'
    Properties:
      VpcId: !Ref MyPrivateVPC
      AmazonProvidedIpv6CidrBlock: true

  MyPrivateSubnet:
    Type: AWS::EC2::Subnet
    DependsOn: VpcCidrBlockIpv6
    Properties:
      AssignIpv6AddressOnCreation: true
      AvailabilityZone: us-west-1a
      Ipv6CidrBlock: !Select [1, !Cidr [!Select [0, !GetAtt 'MyPrivateVPC.Ipv6CidrBlocks'], 256, 64]]
      CidrBlock: 10.255.0.0/24
      VpcId: !Ref MyPrivateVPC

  #IAM roles are basically roles that we allow AWS services to have
  #In this case, we are giving EC2 the role (policy) for Amazon SSM Managegment, which allows it to SSM into an instance
  MyIAMRole:
    Type: AWS::IAM::Role
    Properties:
      Description: This is a role for the CloudFormation-EC2
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      MaxSessionDuration: 43200
      RoleName: RoleForPrivateEC2
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'

  #For AWS Services to access a role, they must be assinged an IAM profile, which we are making now
  MyIAMProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: PrivateEC2InstanceProfile
      Roles: 
        - !Ref MyIAMRole

  MyPrivateEC2Instance:
    Type: AWS::EC2::Instance
    DependsOn: 
      - MyIAMProfile
      - MyPrivateVPC
    Properties:
      ImageId: ami-030cafc5c49b80d00
      IamInstanceProfile: !Ref MyIAMProfile
      InstanceType: t2.micro
      KeyName: Key-pair-4-CloudFormation
      SubnetId: !Ref MyPrivateSubnet

 
 ###########
 #An AWS Systems Manager document (SSM document) defines the actions that Systems Manager performs on your managed instances.
  #You can run the documents, which are usually scripts, through AWS CLI, or the AWS Systems Manager UI
  #THIS IS NOT NECESSARY TO CONNECT TO AN INSTANCE WITH SYSTEM MANAGER. ALTHOUGH WE CAN ASSOCIATE IT TO THE INSTANCE IF NEEDED
  MySSMDocument:
    Type: AWS::SSM::Document
    Properties:
      Content: 
        schemaVersion: "2.2"
        description: "Document to allow SSM access to EC2 instance"
        parameters:
          Message:
            type: "String"
            description: "Example parameter"
            default: "Hello World"
            allowedValues: 
            - "Hello World"
        mainSteps:
          - action: "aws:runPowerShellScript"
            name: "example"
            inputs:
              timeoutSeconds: '60'
              runCommand:
              - "Write-Output {{Message}}"
      DocumentFormat: YAML
      DocumentType: Command

  MyInstanceAssociation:
    Type: AWS::SSM::Association
    DependsOn:
      - MySSMDocument
      - MyPublicEC2Instance
    Properties:
      Name: !Ref MySSMDocument             # -Name 'ad-join-domain' in PowerShell
      Parameters:
        Message:
          - "Hello World"
      Targets:
        - Key: InstanceIds                 # ← case-sensitive; use "InstanceIds"
          Values:
            - !Ref MyPublicEC2Instance     # ← injects the i-... ID at deploy time