
  MyRDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: '20'
      AssociatedRoles: 
        - 'AWSServiceRoleForRDS'
      AvailabilityZone: 'us-west-1a'
      DBInstanceClass: 'db.t2.micro'
      DBInstanceIdentifier: 'rds-from-cloudformation'
      DBName: 'CloudFormationDB'
      DBParameterGroupName: String
      DBSecurityGroups: 
        - String
      DBSnapshotIdentifier: String
      DBSubnetGroupName: String
      DBSystemId: String
      DedicatedLogVolume: Boolean
      DeleteAutomatedBackups: Boolean
      DeletionProtection: Boolean
      Domain: String
      DomainAuthSecretArn: String
      DomainDnsIps: 
        - String
      DomainFqdn: String
      DomainIAMRoleName: String
      DomainOu: String
      EnableCloudwatchLogsExports: 
        - String
      EnableIAMDatabaseAuthentication: Boolean
      EnablePerformanceInsights: Boolean
      Engine: String
      EngineLifecycleSupport: String
      EngineVersion: String
      Iops: Integer
      KmsKeyId: String
      LicenseModel: String
      ManageMasterUserPassword: Boolean
      MasterUsername: String
      MasterUserPassword: String
      MasterUserSecret: 
        MasterUserSecret
      MaxAllocatedStorage: Integer
      MonitoringInterval: Integer
      MonitoringRoleArn: String
      MultiAZ: Boolean
      NcharCharacterSetName: String
      NetworkType: String
      OptionGroupName: String
      PerformanceInsightsKMSKeyId: String
      PerformanceInsightsRetentionPeriod: Integer
      Port: String
      PreferredBackupWindow: String
      PreferredMaintenanceWindow: String
      ProcessorFeatures: 
        - ProcessorFeature
      PromotionTier: Integer
      PubliclyAccessible: Boolean
      ReplicaMode: String
      RestoreTime: String
      SourceDBClusterIdentifier: String
      SourceDBInstanceAutomatedBackupsArn: String
      SourceDBInstanceIdentifier: String
      SourceDbiResourceId: String
      SourceRegion: String
      StorageEncrypted: Boolean
      StorageThroughput: Integer
      StorageType: String
      Tags: 
        - Tag
      Timezone: String
      UseDefaultProcessorFeatures: Boolean
      UseLatestRestorableTime: Boolean
      VPCSecurityGroups: 
        - String
--------------------------

#Security group egress rules---------------------
  SecurityGrouEgressForEC2toAll:
    Type: AWS::EC2::SecurityGroupEgress
    DeletionPolicy: Delete
    Properties:
      Description: 'This rule allows outbound SSH traffic from the EC2 instance to all'
      GroupId: !Ref MyEC2SecurityGroup #Security group ID
      #GroupName: 'sg-for-ec2-to-all' #Security group name
      IpProtocol: '-1' #-1 means all protocols
      CidrIp: "0.0.0.0/0" #Allows all IP addresses

  SecurityGroupEgressForEC2toDB:
    Type: AWS::EC2::SecurityGroupEgress
    DeletionPolicy: Delete
    Properties:
      Description: 'This rule allows outbound MySQL/Aurora traffic from the EC2 instance to the RDS instance'
      FromPort: 3306
      GroupId: !Ref MyEC2SecurityGroup #Security group ID
      #GroupName: 'sg-for-ec2-to-rds' #Security group name
      ToPort: 3306
      IpProtocol: 'tcp'
      CidrIp: 0.0.0.0/0 #Allows all IP addresses (For now, but should be restricted in a real-world scenario)

  SecurityGroupIngressLocaltoEC2:
    Type: AWS::EC2::SecurityGroupIngress
    DeletionPolicy: Delete
    Properties:
      CidrIp: '177.240.101.188/32' #My local IP address
      Description: 'This inbound rule allows SSH traffic from my local IP to the EC2 instance'
      FromPort: 22
      GroupId: !Ref MyEC2SecurityGroup #Security group ID
      #GroupName: 'sg-for-local-to-ec2' #Security group name
      IpProtocol: 'tcp'
      ToPort: 22
